### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by mishushakov** [stepci/liquidless#1]
We'll be building something which is similar to [Liquid](https://shopify.github.io), but less powerful. Should be perfect for templating configuration files in JSON or YAML

Which parts of Liquid we will support:

- Variables
- Filters

Besides that, we should be able to work natively with JavaScript objects without having to convert them to strings first and parsing them again afterwards

Example (strings):

```js
renderTemplate("Hello, {{world}}", { world: "world!" })
```

Produces following:

```
Hello, world!
```

Example (object):

```js
renderTemplate({ hello: "{{world}}" }, { world: "world!" })
```

Produces following:

```js
{ hello: "world!" }
```

Additionally, we should be able to use filters (and provide custom filters!):

Example:

```js
renderTemplate("Hello, {{world | uppercase}}", { world: "world!" })
```

Produces following

```
Hello, WORLD!
```

**Comment by fmalk** [comment]
Packages you should take a look:

https://www.npmjs.com/package/json-templates

https://www.npmjs.com/package/obj-template

Both work with objects, but no filters or piping. Both look like lodash' _.template() for objects.
If you're interested in parsing the entire file (JSON or YAML) then using proper tokenizer like Liquid should be the way to go. A simple object or string would then be just a smaller version of the general case.

**Comment by mishushakov** [comment]
Thanks!
I'm only interested in replacing string values (of an object)

We still want the liquid goodies though!

Until that happens, I think we could depend on the `json-templates` library

**Comment by mishushakov** [comment]
Hello, I have pushed the code for my Liquid implementation to the repository and updated the runner (https://github.com/stepci/runner/pull/55)

Here are some examples of using `liquidjs-lite`:

```js
import { renderTemplate } from 'liquidjs-lite'

const string = renderTemplate('Hello, {{ world | uppercase | something: 1, 2 }}', { world: 'world!' }, {
  filters: {
    something: (value, args) => value.toLowerCase()
  }
})

const object = renderTemplate({"hello": {"world": "{{world}}"}}, { world: 'world!' })
```

The API is much neater than other packages I tried!

**Comment by fmalk** [comment]
@mishushakov you're aware `const cloned = { ...template }` doesn't deep clone, but it works because you're recursively iterating over nested objects, right? At first it seemed you overlooked this, but on second inspection it shouldn't be an issue.

**Comment by fmalk** [comment]
Also, you're looking for `string | object` but you should also iterate over arrays IMO

**Comment by mishushakov** [comment]
Ahh, yes! I'm not perfect, Fernando!
Will look into it in a minute

I have opened another Issue to add filters: https://github.com/stepci/liquidjs-lite/issues/2
Happy to accept contributions!

**Comment by mishushakov** [comment]
Yeah, arrays are borked, thanks for the tip!

```
const object = renderTemplate([{"hello": {"world": "{{world}}"}}], { world: 'world!' })
console.log(object)
```

Output:

```js
{ '0': { hello: { world: 'world!' } } }
```

Expected:

```js
[{ hello: { world: 'world!' } }]
```

**Comment by mishushakov** [comment]
Fixed in https://github.com/stepci/liquidjs-lite/commit/5a627c5a7676fe066926f25963b4c0c78b41fa99
