### ISSUE TITLE
Render object keys too

### ISSUE THREAD

**Issue by RemiBardon** [stepci/liquidless#10]
I was expecting object keys to be rendered too… but it seems they're not.

Basically what I wanted to do is run a Step CI JSONPath check like `$['${{ captures.jid1 }}'].nickname: ${{ captures.nickname1 }}`.

I think the following changes would suffice, but I haven't been able to test it locally because `npm link` doesn't work as I'd like it to.

```diff
  for (const [key, value] of Object.entries(obj)) {
    const nodeType = getType(value)

+   const transformedKey = renderString(key, flatProps, options)
+
    if (nodeType === 'object' || nodeType === 'array') {
-     transformedNode[key] = transform(value)
+     transformedNode[transformedKey] = transform(value)
    } else if (nodeType === 'string') {
-     transformedNode[key] = renderString(value, flatProps, options)
+     transformedNode[transformedKey] = renderString(value, flatProps, options)
    } else {
-     transformedNode[key] = value
+     transformedNode[transformedKey] = value
    }
  }
```

**Comment by mishushakov** [comment]
You don't need npm link, just add additional test-case which should fail in the current version but pass after your change

**Comment by RemiBardon** [comment]
Oh right you have tests 🙄 I'm so not used to JS devs writing tests 🥲
