### ISSUE TITLE
Add more filters

### ISSUE THREAD

**Issue by mishushakov** [stepci/liquidless#2]
We want to support more filters

Reference:
https://shopify.github.io/liquid/
https://liquidjs.com/filters/overview.html

Source code:
https://github.com/stepci/liquidjs-lite/blob/main/src/filters.ts

**Comment by fmalk** [comment]
I can take this one. I'll do a PR.

**Comment by blagerweij** [comment]
See PR #9 , I've implemented most of the Liquid filter functions for strings. I'll also update the README docs.
